# 📚 Are Causal Map and causal mapping for you?


So, you’ve taken a look at the **[features of the app](#xfeatures)**, and you’re getting excited about creating maps – but is your project right for it?

  Use Causal Map if you:

  - have a relatively large amount of narrative data (enough to provide at least 20-30 causal links)
  - need help to organise a large number of links and summarise them into an overview or synthesis
  - have information from more than one source (for example different respondents, different documents, or different places in one document) and the information about the source is important to you: they aren’t all interchangeable
  - are interested in possible differences between the sources and groups of sources – and/or you don’t necessarily have a preconceived idea of the contents or boundaries of the map
  - want to capture what your sources actually say, systematically and transparently

  Causal Map map is not suitable if you:

  - only have a relatively small map which you can manage with traditional tools for drawing network diagrams (e.g. PowerPoint, [kumu.io](http://kumu.io) etc.)
  - need to analyse quantitative data and/or need to do precise mathematical modelling, e.g. of future states of a system under certain conditions
  - would like to sketch out a plan (e.g. Theory of Change or similar) without much reference to the different sources underpinning each link

