# Want to do your own coding?

The workflow is usually like this:

1. UPLOAD: Create a new empty file and upload some narrative data in the form of paragraph-length chunks called `statements`.
2. CODE: View your data statement by statement, and highlight any causal claims within it, telling the app what is the cause ("influence") and what is the effect ("consequence") for each claim. We call this process "coding".
3. ANALYSE: When you've coded a lot of causal claims, you can analyse them to make different kinds of maps and answer different research questions.

### Accounts

To do some coding, you'll need an account.

**Free accounts**

You create an account just by logging in. You can create a new file and do some coding and analysis. You can code up to 50 links for free.

**Paid subscriptions**

Find the [subscription option](https://causalmap.app/subscriptions/) which is right for you. To cancel, renew or manage your subscription see this [section](#xmanage_your_subscription).

If you have a paid subscription, make sure you used the email you use to login is the same as the one for which you have a subscription. 

