#  📚 Glossary{#glossary}

## Generic terminology for causal mapping

| Term | **Definition** |
| ---------- | ------------------------------------------------------- |
| **Active filter bar** | This is the first white bar in the filters panel, if your filter is there it is active. |
| **All filter bar** | This is the second white bar in the filters panel, if your filter is there it is not active, or it is active but can also be used again. |
| **Bundle** | You can bundle links or factors. Bundling factors merges factors containing a chosen word or phrase. You can also bundle links which are between the same influence and consequence factors, which are usually mentioned in different statements by different sources. A thicker line or a label can be used to show the number of links in the bundle. |
| **Causal links** | Causal links are the links between the consequence and influence factors. Each link represents a casual claim. |
| **Combining opposites** | When we combine any pairs of factors which are opposites. This means merging two factors which are identical apart from one starts with a '~', to indicate a negative. On print view the link will show green and pink to indicate that both the positive and negative of the factor is true. |
| **Contrary factor** | With a pair of opposite factors like `Progress` and `~Progress`, we call `Progress` the *ordinary* factor and we call `~Progress` the *contrary* factor. (We prefer this terminology to, say, "negative factor" as it has fewer unwanted connotations: contrary factors don't have to be bad.) |
| **Consequence factor** | A causal factor at the end of a link, that has been influenced by another factor. |
| **Field** | Additional data associated with a statement such as respondent ID number, respondent age or question number. |
| **Flags** aka themes             | A recurring subject found within the factor labels i.e. farming or health. Often we use symbols like # to make sure that the flags are uniquely searchable. |
| **Hierarchical coding** | Nested factors (see below) put factor labels in a hierarchy from more general to specific. [See more here.](#simplifying) |
| **Hybrid format** | (Mostly used in QuIP/BSDR coding.) When importing data into Causal Map, a data table in hybrid format has some rows which are statements and some which are metadata. |
| **Influence factor** | A causal factor at the beginning of the link, that affects another factor. |
| **Mapfile**, **File** | When working in Causal Map, all your original data (the statements, source and question data) as well as the coding you have done (factors and links) are stored together in one file which we call a **mapfile**, or just **file**. |
| **Memos**               | You can make short notes or memos on each statement, as well as about each causal link, each factor, each source, each question and the project globally. |
| **Nested factors** | Factor labels can be nested meaning there are higher level factors i.e <u>New intervention; midwife training; hand washing instructions</u>. [See more here.](#simplifying) |
| **Original links** | Often, there is more than one link between any pair of factors. We can call these the original links especially when we bundle them together for display purposes so they visually look like one. In this case we can say that the bundled link on the map actually consists of several original links. |
| **Shortlink** | A weblink (URL) to a causal map which has been shortened, usually to make sharing it easier. You can easily make [shortlinks](#xshortlinks) using the dashboard. |
| **Statement** | Refers to each individual piece of text to be coded in Causal Map, usually this is a sentence, a paragraph or a few paragraphs. Each statement has an ID; a number like 1, 2, 3 etc. |
| **Source** | Sources are where your statements come from, this could be respondents you have interviewed or documents you have collected. |
| **Weblink** | A complete URL like https://causalmap.shinyapps.io/CausalMap2/ |

