# Is Causal Map for me?


So, you’ve taken a look at the **[features of the app](https://causalmap.app/the-app/)**, and you’re getting excited about creating maps – but is your project right for it?

  Use Causal Map if you:

  - have a relatively large amount of narrative data (enough to provide at least 20-30 causal links)
  - need help to organise a large number of links and summarise them into an overview or synthesis
  - have information from more than one source (for example different respondents, different documents, or different places in one document) and the information about the source is important to you: they aren’t all interchangeable
  - are interested in possible differences between the sources and groups of sources – and/or you don’t necessarily have a preconceived idea of the contents or boundaries of the map.
  - want to capture what your sources actually say, systematically and transparently

  Causal Map map is not suitable if you:

  - only have a relatively small map which you can manage with traditional tools for drawing network diagrams (e.g. PowerPoint, [kumu.io](http://kumu.io) etc.)
  - need to analyse quantitative data and/or need to do precise mathematical modelling, e.g. of future states of a system under certain conditions
  - would like to sketch out a plan (e.g. Theory of Change or similar) without much reference to the different sources underpinning each link

## Prerequisites for using the app

The app is tested on Chrome and Firefox on Mac and Windows, and Safari on Mac, and the new Edge on Windows, and it should work fine on Chrome, Chromium and Firefox on Linux. 

You need a screen with a large resolution, preferably HD or better. It won’t work well on tablet or phone. You will probably want to zoom out to about 90% (in Chrome, press Ctrl – once or twice) to make sure everything fits on the screen. You may also like to view the app "full screen" – how to do this depends on your browser and operating system; on Chrome on Windows, press F11.

As Causal Map is a web application, you will also need a reasonably reliable internet connection. 

