# ⚡ 💻 The Coding Panel: creating factors and links

Qualitative causal mapping involves taking passages of text, e.g. from interviews or documents, and identifying sections which make causal claims. We highlight each of these sections and specify a causal factor at each end of each link (for example Lost job or Went hungry). This means creating a new factor or reusing an existing one. Usually we create these factors inductively as we code, and revise and review and consolidate them as part of the process, as with any other kind of qualitative content analysis. This section is about how to create factors and their labels.


In Causal Map, a factor *is* its label. Once you create a label, there is nothing else to add.

##  Create and edit links in the app

To code a causal link, - With your mouse, highlight a piece of text within the statement which makes a causal claim.

- Watch how that passage is copied for you into the “Quote” window below. (Usually you don't need to think about his window: you can edit the text if you really need to but it has to remain an exact quote of one part of the text or you will get a warning.) - Start to type the name of the influence factors at the **start** of the link(s) which you are going to make, in the first drop-down menu.

- If there is an existing factor which matches what you want, you can select select it.

- Otherwise you will create a new factor with the contents of what you have typed; finish what you have typed with a comma or a tab character if you want to continue to select or create another factor.

- If you want to create more than one link, you can select or create additional factors in the same box.

- When you have finished, press Enter.

- Repeat the process in the other box to specify the factors at the **end** of the link (or ends of the links).

- Press the green Save button which is now active.

- The link is created in the Map window, colour-coded with the quote which is now highlighted on the left. If you mouse over the highlighted quote, the link in the map is activated.

To edit an existing link, - Click on it in the Interactive Map - Make any adjustments in the left panel, e.g. change the influence factor (in the first box), and/or the consequence factor (in the second box). You can change the quoted text just by re-highlighting the correct passage in the statement panel above in the same way that you made the original highlight.

- Press the green Save button.

**NOTE**: your factor names should not contain semicolons **;**. Semicolons are special, they are used for hierarchical coding.

After beginning to create links between factors, one will notice already-coded factors will appear in the dropdown menus in the to and from factor boxes. For added convenience, the most frequently coded factors will appear at the top of this list.

## Using memos and hashtags

Qualitative coding usually involves making notes and memos, and you can do this in Causal Map too.

Hashtags are available as a special kind of memo when coding a link: you can use them to provide any kind of additional information:

- where a link is only relevant in a particular context
- where a link is only a hypothesis
- where a link is only projected for the future
- to tag links you want to come back and review
- to add other qualifying information like “source seems unsure.”

As usual in Causal Map, you can apply one or more hashtags, and you can either select existing hashtags or create new ones on the fly.

Later, you can [filter the map](https://guide.causalmap.app/analysis.html#filtering-the-map-by-link-hashtag-memo) to show only links containing specific hashtags (or parts of hashtags), and also for links which do *not* contain specific hashtags or parts of hashtags.

