# Features of Causal Map

## Main features of Causal Map

- Code causal claims in the form A –> B
- Code multiple claims at once
- Code additional claims as a continuation of previous claim (“chaining”)
- Import data (and meta-data about your sources) in different formats
- Add memos and hashtags
- See a summary of all statements from a specific source
- View additional information about each statement (e.g. question and respondent characteristics)
- Create simple or hierarchical factor labels
- Edit many factors and links at once in a powerful bulk editor
- Filter the global map by: Current statement; Factor label; Link (quote, hashtag, memo etc); Statement (text, additional data e.g. respondent characteristics)
- Trace paths from one set of factors to another
- Use the interactive viewer to edit your map
- View and export print-quality maps
- View all quotes for a specific view, and get a smart summary
- Create detailed tables: Factors; Sample; Questions; Closed questions
- Calculate **Robustness of Argument** for causal paths between sets of factors
- Download/export your data in different formats
- Share files with others for viewing or editing
- Code additional properties of links like strength and certainty, or mark pairs of factors which are opposite to one another

## Additional new features in Causal Map 2

- Anyone can use it, and it is free for small projects

- Make your findings more visible with conditional formatting

- Bundle links by stakeholder, by district, by question ...

- Really nice infinite versioning, so you can restore any single change you ever made to a file from any timepoint. This isn't just backups, it is every single change.

- Much easier to import and manage your data

- You can import a standard-format Excel file into cm2, and download it again, and edit it, and upload it again ("round-tripping"). You can also include any additional fields aka columns you want and they will be imported and available for searching, conditional formatting etc. 

- Build a map by importing any combination of tables or just some of them - factors, links, sources, questions & statements, in any order at any time and it should all just work

- You can edit the tables directly

/*- The URL in your browser always points to the map and filters you are using right now, so a) if you refresh your browser or go away for a while, you can always come back to where you left off, and b) you can share or save the link for later*/

- A Google Chat room for support

- Bundle factors

- Bundle links by field

- Clickable legends and ordinary-language explanations of filters

- All outputs recreatable from the filters

- merging maps:

  - You can use the merge_map filter to temporarily merge other files into the current file if you wish. You can share a link to that merge and revisit it.  Viewing a merge of file A and file B will take longer, so you will probably want to save the merged file as a new file.
  - The tables (factors, links etc) have a new field called factor_map_id etc, which you can use to visualise the merge e.g. by presenting links in a different colour according to their source.

- manage all your files at once with a comprehensive file manager from which you can restore, lock, delete, archive and share any file (not just the current file).

- log in to the same or different maps from the same or different accounts, including from multiple browser tabs.

- collaborate on a file in almost real time.

- view, filter, sort etc and directly edit all the tables - factors, links, sources, questions & statements - making up a map. These tables provide all the existing tables functionality plus more. So you will be able to do things like, say, find all the links with a certain hashtag and delete them.

- delete factors and edit and delete links directly from the interactive map

- create a new blank file

- clone an existing file under a new name, containing all the current factors or only including the factors currently visible if you wish.

- If border colours are not set, or all the same, borders are superfluous so the border size is set to zero in Print view

- New colour scales which are colour-blind friendly and make sense when printed on black & white printers

- Like Print View, if Interactive View is given a very big map with lots of links, it now bundles up the links so that it loads faster (you can still view a random quote from the bundle when you hover over a link)
- When you edit a link, you are able to replace it with more than one link if you wish, e.g. you can edit a link A→B and replace it with A→B and A→C by typing both B and C in the consequence factor box. Actually, when you edit a link, CM2 loads up the details from the old link into the coding panel, and if you press 💾, the old link will be deleted and the new one added. You can cancel this process, as in cm1
- Less than, greater than: The find factors, find links, find statements filters allow comparisons like greater than, so it is possible to do things like find statements with id greater than 100.
