# 💻 The Factor Editor 

## Editing factor labels in the Factor Editor

Click inside the editor and retype the factor labels however you want. You can rewrite entire lines, but you can't delete or add lines.

Then hit Update.

**TIP**: press Ctrl F (Cmd F on Mac) to find or Ctrl H (Cmd alt F on Mac) to replace.

**TIP**: Reformulate factor labels so that some common themes come *first*.

**TIP**: Use flags like “Problem!” or “#innovation”, unique words which are easy to search for, to make it easy to find particular kinds of factor within the editor and elsewhere.

**TIP**: Merge your factors. You have two or more factors which are more or less the same?

- pick the best version, tweak it if necessary, and then copy the whole line
- go to one of the other versions, and replace the label with the label you copied, taking care not to delete or add lines
- repeat with any other similar lines, so that all the similar labels are now exactly the same
- don't forget to press Update!
- … these factors with the common label will all be combined into one

## Splitting/recoding existing factors: Use the **Split** switch.


Usually when you rename your factors, the names change everywhere. If you switch on “Split”, each factor you rename will be split into a new factor (with the new name which is used only for the links in the current view/filter), and the original factor which is unchanged. This is useful for example if you find you have merged some ideas together too quickly into one factor and you want to split it back into two.

Suppose you have coded both “I bought a cow”“ and "I bought a sheep” as *bought livestock* and then you change your mind, you can go back to the statement with “I bought a cow”, and in this tab you switch on “Split” and recode *bought livestock* back to *bought cow*. If you didn't switch on “Split”, the other quote (“I bought a sheep”) would also be recoded as *bought cow*, which isn't what you want.

Bear in mind that if you merge several factors into one, this may mean you get duplicate or triplicate links between the same pairs of factors.

## Advanced editing tips

- Go to the next mention of a selected word/sentence: **Ctrl K,or Cmd G on Mac**. Add SHIFT to these shortcuts to find the *previous* mention.
- Add next occurrence of selected word/sentence to multi-selection: **Ctrl-Alt-Right,or Cmd-Option-Right on Mac**. Use **Ctrl-Alt-Left / Cmd-Option-Left** to add *previous* occurrence.
- The app will help you consistently type words you have already used with autocomplete. Or just ignore it if you want.
- Multicursor: Ctr alt Up/Down: edit multiple lines at once
