# 📚 Clustering sources{#cluster-sources}

🧪 This filter

```
cluster sources n_clusters=all
```

... groups all the sources in the file (as currently filtered) into clusters which are similar in terms of the maps they tend to produce. So the maps for each cluster should be maximally different from one another.

This filter finds three separate solutions with two, three and four clusters. It's your job to decide which (if any) is the solution which is best and easiest to interpret.

In future we will provide output to crosstabulate the clusters with other key fields like gender and district, and to automatically produce maps for each cluster, surprise maps, differences tables, etc.

The algorithm is quite simple, it simply treats the links table for each source as a one-dimensional binary vector of length equal to the square of the number of factors. It's a binary vector, so multiple mentions of the same bundle of links by the same source are no different from a single mention.



 



