# (PART) Extra features {-}

# 🧠 Adding additional information like strength of a link in a causal map: let's keep it simple 

Causal mapping involves modelling people’s causal claims and beliefs as links or arrows between factors. In Part 1 we argued that a causal mapping approach is represented first and foremost by sets of rules which say *how* causal information is encoded by specific features of the elements of the map. In this second Part, we will present some new rules for encoding causal claims within causal maps. We will see that there is no one perfect set of features we can use for encoding all or even a satisfactorily broad selection of all possible causal claims. Even with some quite basic possible features like encoding the “strength” of a causal link, it is not hard to dream up a range of similar but different sets of rules for encoding and manipulating causal maps using this feature. To encode strength of a link, should we use numbers from 0 to 1, or maybe from -1 to +1? If several links point to a factor, should we simply add up the strengths, or use some function which keeps the value of the factor somewhere lower than 1? And so on.

These kinds of problems are common to all attempts to model phenomena. But the problem is particularly acute with causal mapping, especially in causal evidence mapping, where we try to encode many individual claims or beliefs. For example, when viewing actual causal claims we sometimes (but not very often, unless the sources are academics) come across claims about how a set of two or more factors interact to influence another in a way which cannot be captured just by sets of individual links: one of many phenomena sometimes called “non-linear”. For example, "you need fuel AND oxygen AND a spark to get a fire". The trouble is, are we going to activate a whole new set of conventions and rules just to cope with this minority of causal claims? Probably not. 

In practice, we suggest that any one causal map should select an only *one* approach (only *one* set of rules for encoding causal ideas with specific features of the map’s elements) and that this approach should be no more complicated than is necessary to encode most of the causal claims. Mixing approaches within a single map is endlessly tiresome and complicated. It is not a good idea to introduce an additional feature (like "C is necessary but not sufficient for E") just to cope with a minority of causal claims in the map. 

