# Spotlight: Compatible and incompatible factors in storylines

Sets of diverging storylines can also be seen as examples of causal maps, as they are networks of events or situations connected by links which are at least in a weak sense causal.

What happens when stories diverge in ways which could be either mutually compatible or mutually exclusive? 

Example: a scenario starting with Trump's nomination as Republican candidate in 2024. Leading on from that you might have (a) a branch in which he's actually elected for a second term and leading on in turn from that you'd have many nodes which are dependent on his election e.g. issuing various orders. And likely you'd have another branch (b) in which he is not elected, building on which you'd have other nodes. Plus, you might have two other branches starting with (c) he issues an order on fracking and (d) he issues an order on space travel.

Now branches A and B are incompatible, whereas C and D are not. In many traditions of causal mapping you'd actually want to combine A and B into one node but somehow make the arrows coming out of it have in some sense opposite polarity. I'm not saying you should, I'm just pointing out that A and B are in a sense two opposite sides of the same coin.

There is a way to look at this kind of divergence in terms of the structural properties of graphs: separating hierarchical clusters. The branches going off from A and B are likely to have little overlap, whereas some nodes in the other pairs of branches might be thematically more similar to one another. To be sure, in a scenario-building approach like ParEvo you aren't going to get stories literally recombining, but they might be close in content. I think there's a reference here to the "hieclust" algorithm as presented by Ackerman and Eden.

There's something fundamental about the difference between A and B: These sets of nodes just don't feature in one another's universes. Whereas, with a more compatible divergence, they're all still in a sense part of the same world.