# Spotlight: Cases, variables and percentages in causal mapping?

In causal mapping we tend to in most cases steer away from any kind of "75% said ..." statements. It isn't just that we don't tend to use representative samples. 

The point is deeper, namely that most sorts of causal map, the concept of a variable and even the concept of a "case" is a bit vague. In a causal map in general, even one combined from individual inputs, you don't have a clearly defined "case", and correspondingly you don't have clearly defined variables, which makes it more radical and less structured than, say, the world of QCA. 

Some causal maps are elicited as a group consensus about high-level variables like “economic growth”; others are constructed such that all the causal factors represent variables at the level of the individual respondent such as “improvements in nutrition in my household”. Some QuIP maps are however heterogeneous in this respect. The causal chains in individual stories are random walks. Maybe respondent R mentions a factor like “flooded fields” somewhere in a causal chain but respondent S mentions it nowhere. From this we cannot conclude that flooded fields were not a factor in any causal link for respondent S. We don’t even know if respondent S has fields which might get flooded. If they do, are they specific to this respondent or are they shared across a whole village? Part of a village? In this kind of causal map, our sense of what is a “case” is quite vague, and it is also, correspondingly, difficult to think of the causal factors as variables which are defined for every case. We can only find out whether a causal factor really is a variable which makes sense for each respondent considered as a case (or perhaps for some other set of cases, such as “school which the respondent’s children attend”) by reading the narratives and constructing the cases and variables for ourselves.
This soft approach to cases and variables make causal mapping idea for what are sometimes called “complex” situations or systems. However it makes it more difficult to report some kinds of metrics and draw some kinds of inferences from causal maps. 

 
that mean that for the other 16, agriculture was not a cause? Not really. Not even if we assume that our analysts identify and name common factors between respondents perfectly. This vagueness becomes even clearer as we go further up the chain - what about the 4 who mentioned a link between gender roles and agriculture, and the 20 who didn’t?

The reason that even the notion of cases partly breaks down is because while households by all means may always answer on the individual level (“My household / my crops / my attendance at training” etc.) but often in fact they name causal factors which do not live on this level (like “My village’s water supply / roads”) or even things like “the new law” or potentially non-changes like “Unemployment.” Suddenly, the households are not loci of varying information but loci of opinions about things which do not vary at household level - and often they may be something in between (“roads in my half of the village”; “for us pig farmers..”).
 



More generally, in a causal map drawn up from, say, a literature review, the questions of whether there are any variables or cases is something which only gradually emerges / gets constructed. Sometimes we might find that some areas of a map start to contain cases and variables (perhaps we have data from several similar schools), and perhaps there are different such areas, and they might even overlap (perhaps we have data concerning mothers and data concerning fathers). 







