# 💻 Uploading/Importing your statements and related data{#import}

The only data you need to provide is a table of statements as the only tab in an xlsx file. Your file must have a header row with the names of the fields.

## Making a basic statements table

You can create a table from a Word document. 

Each paragraph in your Word document will become one statement, so make sure your Word document is already structured so this will work for you. Delete any double paragraph breaks in Word (i.e. delete any empty paragraphs). If you want some short paragraphs to appear together as one longer statement, delete the paragraph breaks between them.

Then

- Copy all the text from your document
- Create a fresh spreadsheet file in Excel (or LibreOffice Calc or similar) and select cell A2
- Paste your text.
- Type the word “text” as column header in cell A1.
- Check the statements are the way you want them. You can ignore any formatting, pictures etc which might also have been pasted in because these will disappear in the next step.

The statements are the texts which appear one by one by one in the Code & View tab, for you to read and code. Each statement is one row in your file.

If you want to import interviews which are several pages each, you should break each interview into several statements. Ideally a statement consists of between one and five paragraphs – enough to fit on the left-hand side of the Code & View tab when it is displayed there. Usually your text breaks up naturally into sections, for example the interviews might be responses to a number of questions, so your statements might consist of one or a few paragraphs for each question.

We strongly recommend that you don’t try to import statements which are longer than 2500 characters or 500 words. It is harder to code very long statements.

Your statements file must have at least one column with the text of the statements and the header for this column must be “text.” Other columns will be treated as additional data.

The only required field in your data table is the text of each statement, like this.

**text**

---

Lorem ipsum …

---

Ipsum lorem …

---

Lorem sunt …

---

Asdf …

---

…

---

## Dealing with additional information



However you nearly always have additional information, first and foremost about the source, for example about the respondent who provided the information, or about the context of the information, e.g. if this statement was a response to a question, what is the question number, or the text of the question, or the name of the interviewer. 

### Providing additional data as additional fields in the statements table. 

You can think of additional data as just any additional fields in the statements table. If you provide all of these fields when you import your data, that’s fine, there is nothing more to do. For example, you can import the table below instead of the table above. At the moment the app understands only text fields and numerical fields. It will treat dates and currency as ordinary numbers.

Probably, each respondent belongs to one “village,” each village to one region and each village has one population figure. But the app does not need to know that.

In each case, the app also adds a “statement ID” field, numbering the statements 1, 2, 3 etc. to help keep track of them.

However, it is better to import additional data about your sources (and questions) using separate tables.

### Uploading/importing Source (Respondent) and Question data separately

Often it isn’t convenient to provide this whole table yourself. Often you think in terms of smaller sub-tables. For example you might have one table just with the statements and the respondents (say, there are 20 statements per respondent and 10 respondents, so a total of 200 statements), and another table with 20 rows giving information about each respondent, say with just the field “Village” or maybe with more fields. The app can help you combine this data with the statements. Here is an example.

### Uploading/importing Source (Respondent) and Question data separately

Often it isn’t convenient to provide this whole table yourself. Often you think in terms of smaller sub-tables. For example you might have one table just with the statements and the respondents (say, there are 20 statements per respondent and 10 respondents, so a total of 200 statements), and another table with 20 rows giving information about each respondent, say with just the field “Village” or maybe with more fields. The app can help you combine this data with the statements. Here is an example.

 

Suppose you already uploaded just this table

| **text**    | **source_id** |
| ----------- | ------------- |
| Lorem ipsum | 1             |
| Ipsum lorem | 1             |
| Lorem sunt  | 1             |
| asdf        | 2             |
| …           | …             |

 

The app already added an additional statement_id field for you.

| **statement_id** | **text**    | **source_id** |
| ---------------- | ----------- | ------------- |
| 1                | Lorem ipsum | 1             |
| 2                | Ipsum lorem | 1             |
| 3                | Lorem sunt  | 1             |
| 4                | asdf        | 2             |
| …                | …           | …             |

(Or, suppose you already imported QuIP data as described elsewhere.)

Suppose you now have additional information about the **sources**, like this.

| **source_id** | **Village** |
| ------------- | ----------- |
| **1**         | Bigville    |
| **2**         | Smallville  |
| **3**         | Bigville    |
| **…**         | …           |

Upload this data by clicking “Sources” in the data editor on the right (where you will see any existing data for your sources) and then selecting your csv file.

If you are uploading additional data about *Sources* remember to click the Sources button first. If you are uploading additional data about *Questions* remember to click the Questions button first.

The app merges the information like this:

| **statement_id** | **Text**    | **source_id** | **Village** |
| ---------------- | ----------- | ------------- | ----------- |
| 1                | Lorem ipsum | 1             | Bigville    |
| 2                | Ipsum lorem | 1             | Bigville    |
| 3                | Lorem sunt  | 1             | Bigville    |
| 4                | Asdf        | 2             | Smallville  |
| …                | …           | …             | …           |

 

The procedure is exactly analogous for uploading additional information about your questions, for example question text, or questionnaire section.


