# Uploading additional data like age, gender{#import-additional-data}

You often have additional information to upload, as well as the actual statements you want to code. Often this additabout the source, for example about the respondent who provided the information, or about the context of the information e.g. what was the question asked or the name of the interviewer. 

Additional data is just any additional fields related to each statement. 

You can include them when you do your [initial upload](#ximport), or later, using round-tripping. 

- When you upload in [Standard Format](#ximport2excel), you provide additional data fields like gender as  *columns* in the `sources` worksheet alongside your `statements` worksheet.

- When you upload in [Wide format](#xupload-google), you provide additional data fields like gender as additional *columns* in the file you upload.

- When you upload in [Hybrid format](#ximport-quip), you provide additional data fields like gender as additional *rows* in the file you upload. 

- When you upload [Text files](#ximport2excel), the only additional data you can only provide is the ID of question and/or respondent. You will probably want to later add more information about these respondents using round-tripping.

Whatever format you use to upload your data, you can always continue to add data including additional data like age, gender etc using [roundtripping](#xroundtripping). However, remember that any data you upload will [overwrite the existing data](#import-general-principles) -- so if you only want to update your sources data, make sure you delete any other worksheet in the file you upload to leave only the `sources` worksheet.

 

