# Keyboard shortcuts {#xkeybarod}

## General

There are only a couple of shortcuts so far:

- Esc should get you out of any modal dialogue
- Alt+q opens the Gallery



## Factor Editor and Advanced Editor

For more information about working with the Ace editor, visit [https://ace.c9.io/#nav=about](https://ace.c9.io/#nav=about).

Ace provides the following keyboard shortcuts to streamline the coding process.

### Line operations

| Action              | Windows/Linux  | Mac                                     |
| :------------------ | -------------- | --------------------------------------- |
| Remove line         | Ctrl-D         | Command-D                               |
| Copy lines down     | Alt-Shift-Down | Command-Option-Down                     |
| Copy lines up       | Alt-Shift-Up   | Command-Option-Up                       |
| Move lines down     | Alt-Down       | Option-Down                             |
| Move lines up       | Alt-Up         | Option-Up                               |
| Remove to line end  | Alt-Delete     | Ctrl-K                                  |
| Remove to linestart | Alt-Backspace  | Command-Backspace                       |
| Remove word left    | Ctrl-Backspace | Option-Backspace, Ctrl-Option-Backspace |
| Remove word right   | Ctrl-Delete    | Option-Delete                           |
| Split line          | ---            | Ctrl-O                                  |

### Selection

| Action                     | Windows/Linux    | Mac                 |
| :------------------------- | ---------------- | ------------------- |
| Select all                 | Ctrl-A           | Command-A           |
| Select left                | Shift-Left       | Shift-Left          |
| Select right               | Shift-Right      | Shift-Right         |
| Select word left           | Ctrl-Shift-Left  | Option-Shift-Left   |
| Select word right          | Ctrl-Shift-Right | Option-Shift-Right  |
| Select line start          | Shift-Home       | Shift-Home          |
| Select line end            | Shift-End        | Shift-End           |
| Select to line end         | Alt-Shift-Right  | Command-Shift-Right |
| Select to line start       | Alt-Shift-Left   | Command-Shift-Left  |
| Select up                  | Shift-Up         | Shift-Up            |
| Select down                | Shift-Down       | Shift-Down          |
| Select page up             | Shift-PageUp     | Shift-PageUp        |
| Select page down           | Shift-PageDown   | Shift-PageDown      |
| Select to start            | Ctrl-Shift-Home  | Command-Shift-Up    |
| Select to end              | Ctrl-Shift-End   | Command-Shift-Down  |
| Duplicate selection        | Ctrl-Shift-D     | Command-Shift-D     |
| Select to matching bracket | Ctrl-Shift-P     | ---                 |

### Multicursor

| Action                                                       | Windows/Linux        | Mac                     |
| :----------------------------------------------------------- | -------------------- | ----------------------- |
| Add multi-cursor above                                       | Ctrl-Alt-Up          | Ctrl-Option-Up          |
| Add multi-cursor below                                       | Ctrl-Alt-Down        | Ctrl-Option-Down        |
| Add next occurrence to multi-selection                       | Ctrl-Alt-Right       | Ctrl-Option-Right       |
| Add previous occurrence to multi-selection                   | Ctrl-Alt-Left        | Ctrl-Option-Left        |
| Move multicursor from current line to the line above         | Ctrl-Alt-Shift-Up    | Ctrl-Option-Shift-Up    |
| Move multicursor from current line to the line below         | Ctrl-Alt-Shift-Down  | Ctrl-Option-Shift-Down  |
| Remove current occurrence from multi-selection and move to next | Ctrl-Alt-Shift-Right | Ctrl-Option-Shift-Right |
| Remove current occurrence from multi-selection and move to previous | Ctrl-Alt-Shift-Left  | Ctrl-Option-Shift-Left  |
| Select all from multi-selection                              | Ctrl-Shift-L         | Ctrl-Shift-L            |

### Go to

| Action                 | Windows/Linux  | Mac                        |
| :--------------------- | -------------- | -------------------------- |
| Go to left             | Left           | Left, Ctrl-B               |
| Go to right            | Right          | Right, Ctrl-F              |
| Go to word left        | Ctrl-Left      | Option-Left                |
| Go to word right       | Ctrl-Right     | Option-Right               |
| Go line up             | Up             | Up, Ctrl-P                 |
| Go line down           | Down           | Down, Ctrl-N               |
| Go to line start       | Alt-Left, Home | Command-Left, Home, Ctrl-A |
| Go to line end         | Alt-Right, End | Command-Right, End, Ctrl-E |
| Go to page up          | PageUp         | Option-PageUp              |
| Go to page down        | PageDown       | Option-PageDown, Ctrl-V    |
| Go to start            | Ctrl-Home      | Command-Home, Command-Up   |
| Go to end              | Ctrl-End       | Command-End, Command-Down  |
| Go to line             | Ctrl-L         | Command-L                  |
| Scroll line down       | Ctrl-Down      | Command-Down               |
| Scroll line up         | Ctrl-Up        | ---                        |
| Go to matching bracket | Ctrl-P         | ---                        |
| Scroll page down       | ---            | Option-PageDown            |
| Scroll page up         | ---            | Option-PageUp              |

### Find/Replace

| Action        | Windows/Linux | Mac              |
| :------------ | ------------- | ---------------- |
| Find          | Ctrl-F        | Command-F        |
| Replace       | Ctrl-H        | Command-Option-F |
| Find next     | Ctrl-K        | Command-G        |
| Find previous | Ctrl-Shift-K  | Command-Shift-G  |

### Folding

| Action         | Windows/Linux              | Mac                                      |
| :------------- | -------------------------- | ---------------------------------------- |
| Fold selection | Alt-L, Ctrl-F1             | Command-Option-L, Command-F1             |
| Unfold         | Alt-Shift-L, Ctrl-Shift-F1 | Command-Option-Shift-L, Command-Shift-F1 |
| Fold all       | Alt-0                      | Command-Option-0                         |
| Unfold all     | Alt-Shift-0                | Command-Option-Shift-0                   |

### Other

| Action                 | Windows/Linux        | Mac                        |
| :--------------------- | -------------------- | -------------------------- |
| Indent                 | Tab                  | Tab                        |
| Outdent                | Shift-Tab            | Shift-Tab                  |
| Undo                   | Ctrl-Z               | Command-Z                  |
| Redo                   | Ctrl-Shift-Z, Ctrl-Y | Command-Shift-Z, Command-Y |
| Show the settings menu | Ctrl-,               | Command-,                  |
| Toggle comment         | Ctrl-/               | Command-/                  |
| Transpose letters      | Ctrl-T               | Ctrl-T                     |
| Enter full screen      | Ctrl-Enter           | Command-Enter              |
| Change to lower case   | Ctrl-Shift-U         | Ctrl-Shift-U               |
| Change to upper case   | Ctrl-U               | Ctrl-U                     |
| Overwrite              | Insert               | Insert                     |
| Macros replay          | Ctrl-Shift-E         | Command-Shift-E            |
| Macros recording       | Ctrl-Alt-E           | ---                        |
| Delete                 | Delete               | ---                        |
| Center selection       | ---                  | Ctrl-L                     |




**© Copyright Trivantis** **2019**



Thanks to [Trivantis](https://www.trivantis.com/help/Lectora_Online/4.8/en/HelpHTMLs/Content/16.html) for the list.