# Causal mapping with Excel{#xexcel}

Now we are going to back to the basics of causal mapping. You don't need Causal Map App, or any other dedicated application, to do causal mapping. You can use Excel or any spreadsheet program.

Causal maps store information about links of causal influence between two or more factors alongside the evidence for each link. We call the chunks of text, for example from interview transcripts, which potentially contain claims about causal connections, "statements".

[Here](https://docs.google.com/spreadsheets/d/12eXQDJtvlLO6qRrwbxwvkchfdTNLSbjo/edit?usp=sharing&ouid=112812082380437768869&rtpof=true&sd=true) is an example, it contains example- statements from a newspaper article and an interview concerning flooding and coastal erosion. These links that you see here, otherwise known as an edge-list, the starting point for any causal map. You can clearly see the factors in the first column affect the factors in the second. For example, Column A contains influence factors such as 'high rainfall' which influence the consequence factor in the next column, like 'flooding'. It is these links that are then displayed in a causal map.

You will notice, in this example, that the columns in the links tab are dropdown lists when you click on the triangles in each cell. These dropdown lists are fed from the labels listed in the factors tab. So you can change the options available by editing or adding labels in the factors tab.

Optionally, on the statements tab the statement_id column works in a similar way and is fed by the sources tab. The question_id is fed by the questions tab. So the sheets are programmed to link together. 

You can download the example and play around with it or use it as a template for your own map. 

Also once in excel format causal map becomes compatible with other data visualisation tools like Gephi, and if you want to know more about that check out our video on using the causal map app alongside other data visualisation tools.

You can download this file [here](https://docs.google.com/spreadsheets/d/12eXQDJtvlLO6qRrwbxwvkchfdTNLSbjo/edit?usp=sharing&ouid=112812082380437768869&rtpof=true&sd=true).

