# Video list{#xvideo-list}

These videos are all included at different points in the Guide. If you love videos, here they are again in one place. Feel free to binge. Tip: if you play a video, you can press 'Picture in picture' and then switch to the app, and you can follow (and even resize) the video.
```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/689223728")
```

```{r,echo=F}
knitr::include_url("https://www.youtube.com/embed/S2acbJJ9t7E")
```

```{r,echo=F}
knitr::include_url("https://www.youtube.com/embed/6DBzadDMXew")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/674369121")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/674383670")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/641927229")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/604099226")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/580212681")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/671894620")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/637121851")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/604138709")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/664879474")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/683770170")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/636997200")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/588851236")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/588881701")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/618270513")
```

```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/651173445")
```


```{r,echo=F}
knitr::include_url("https://player.vimeo.com/video/599620015")
```

